# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      env:
        JWT_SECRET: H!JS@G#FFG#s%dfg@sdfdgsdfagDFGDFDAH@#FJK@432?D
        JWT_EXPIRES_IN: 20h
        GOOGLE_MAPS_ACCESS_KEY: AIzaSyDsadPAbIgJa8JNvCGwPWVBY0NUn5MKcoE
        MONGO_INITDB_ROOT_USERNAME: birthmeal
        MONGO_INITDB_ROOT_PASSWORD: birthmeal
        MONGO_DB: Birthmeal
        MONGO_CONNECTION: mongodb
        MONGO_HOST: 45.7.231.52
        MONGO_PORT: 27017
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run deploy
    - run: npm run start
    
