# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: create env file
      run: |
        touch .env
        echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
        echo JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }} >> .env
        echo GOOGLE_MAPS_ACCESS_KEY=${{ secrets.GOOGLE_MAPS_ACCESS_KEY }} >> .env
        echo MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }} >> .env
        echo MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }} >> .env
        echo MONGO_DB=${{ secrets.MONGO_DB }} >> .env
        echo MONGO_CONNECTION=${{ secrets.MONGO_CONNECTION }} >> .env
        echo MONGO_HOST=${{ secrets.MONGO_HOST }} >> .env
        echo MONGO_PORT=${{ secrets.MONGO_PORT }} >> .env
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run deploy
    - run: npm run start
    
