# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: get variables from secret (github actions) and put it on .env file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
        GOOGLE_MAPS_ACCESS_KEY: ${{ secrets.GOOGLE_MAPS_ACCESS_KEY }}
        MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
        MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
        MONGO_DB: ${{ secrets.MONGO_DB }}
        MONGO_PORT: ${{ secrets.MONGO_PORT }}
        MONGO_HOST: ${{ secrets.MONGO_HOST }}
        MONGO_CONNECTION: ${{ secrets.MONGO_CONNECTION }}
        HOLA: ${{ secrets.HOLA }}
        PRUEBA: fhjsdhfjdskfsd
      run: |
        echo HOLA=$HOLA >> $GITHUB_ENV
        echo GITHUB_TOKEN=$GITHUB_TOKEN >> .env
        echo JWT_SECRET=$JWT_SECRET >> .env
        echo JWT_EXPIRES_IN=$JWT_EXPIRES_IN >> .env
        echo GOOGLE_MAPS_ACCESS_KEY=$GOOGLE_MAPS_ACCESS_KEY >> .env
        echo MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME >> .env
        echo MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD >> .env
        echo MONGO_DB=$MONGO_DB >> .env
        echo MONGO_PORT=$MONGO_PORT >> .env
        echo MONGO_HOST=$MONGO_HOST >> .env
        echo MONGO_CONNECTION=$MONGO_CONNECTION >> .env
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run deploy
    - run: npm run start
    
